# NumPy Array 

basic array manipulations:
- <b>Attributes of arrays</b>: Determining the size, shape, memory consumption, and data types of arrays
- <b>Indexing of arrays</b>: Getting and setting the value of individual array elements
- <b>Slicing of arrays</b>: Getting and setting smaller subarrays within a larger array
- <b>Reshaping of arrays</b>: Changing the shape of a given array
- <b>Joining and splitting of arrays</b>: Combining multiple arrays into one, and splitting one array into many

## NumPy Array Attributes

First let’s discuss some useful array attributes. We’ll start by defining three random
arrays: a one-dimensional, two-dimensional, and three-dimensional array. We’ll use
NumPy’s random number generator, which we will seed with a set value in order to
ensure that the same random arrays are generated each time this code is run:


<!-- First let’s discuss some useful array attributes. We’ll start by defining three random
arrays: a one-dimensional, two-dimensional, and three-dimensional array. We’ll use
NumPy’s random number generator, which we will seed with a set value in order to
ensure that the same random arrays are generated each time this code is run: -->

In [16]:
import numpy as np

np.random.seed(0) # seed for reproducibility
x1 = np.random.randint(10, size=6) # One-dimensional array
x2 = np.random.randint(10, size=(3, 4)) # Two-dimensional array
x3 = np.random.randint(10, size=(3, 4, 5)) # Three-dimensional array

print(x1,"\n")
print(x2,"\n")
print(x3)

[5 0 3 3 7 9] 

[[3 5 2 4]
 [7 6 8 8]
 [1 6 7 7]] 

[[[8 1 5 9 8]
  [9 4 3 0 3]
  [5 0 2 3 8]
  [1 3 3 3 7]]

 [[0 1 9 9 0]
  [4 7 3 2 7]
  [2 0 0 4 5]
  [5 6 8 4 1]]

 [[4 9 8 1 1]
  [7 9 9 3 6]
  [7 2 0 3 5]
  [9 4 4 6 4]]]


In [28]:
# Each array has attributes ndim (the number of dimensions), shape (the size of each # dimension), and size (the total size of the array):
print("x1: ndim =", x1.ndim, "shape =", x1.shape, "size =", x1.size)
print("x2: ndim =", x2.ndim, "shape =", x2.shape, "size =", x2.size)
print("x3: ndim =", x3.ndim, "shape =", x3.shape, "size =", x3.size)

x1: ndim = 1 shape = (6,) size = 6
x2: ndim = 2 shape = (3, 4) size = 12
x3: ndim = 3 shape = (3, 4, 5) size = 60


In [31]:
# Another useful attribute is the dtype, the data type of the array
print("dtype:", x3.dtype)
# Other attributes include itemsize, which lists the size (in bytes) of each array element,
# and nbytes, which lists the total size (in bytes) of the array:
print("itemsize:", x3.itemsize, "bytes")
print("nbytes:", x3.nbytes, "bytes")


dtype: int32
itemsize: 4 bytes
nbytes: 240 bytes


## NumPy Array Indexing

Slice indexing:

Similar to the use of slice indexing with lists and strings, we can use slice indexing to pull out sub-regions of ndarrays. You can access the ith value (counting from zero) by specifying the desired index in square brackets, just as with Python lists:

In [12]:
import numpy as np

# Rank 2 array of shape (3, 4)
an_array = np.array([[11,12,13,14], [21,22,23,24], [31,32,33,34]])
print(" ",0, "", 1, "",2, "", 3) # index
print(an_array)

  0  1  2  3
[[11 12 13 14]
 [21 22 23 24]
 [31 32 33 34]]


Use array slicing to get a subarray consisting of the first 2 rows x 2 columns.

In [18]:
a_slice = an_array[:2, 1:3]
print(a_slice)

[[5 2]
 [6 8]]


When you modify a slice, you actually modify the underlying array.

One important—and extremely useful—thing to know about array slices is that they
return views rather than copies of the array data. This is one area in which NumPy
array slicing differs from Python list slicing: in lists, slices will be copies

In [19]:
print("Before:", an_array[0, 1]) #inspect the element at 0, 1  
a_slice[0, 0] = 1000 # a_slice[0, 0] is the same piece of data as an_array[0, 1]
print("After:", an_array[0, 1])  

Before: 5
After: 1000


In [24]:
an_array = np.array([[12,5,2,4], [7,6,8,8], [1,6,7,7]])
# Let’s extract a 2×2 subarray from this

# Let’s extract a 2×2 subarray from this
a_slice = an_array[:2, :2]

# Now if we modify this subarray, we’ll see that the original array is changed
print("Before:\n", an_array)
a_slice[0,0] = 99
print("After:\n", a_slice)


Before:
 [[12  5  2  4]
 [ 7  6  8  8]
 [ 1  6  7  7]]
After:
 [[99  5]
 [ 7  6]]


Creating copies of arrays

Despite the nice features of array views, it is sometimes useful to instead explicitly
copy the data within an array or a subarray. This can be most easily done with the
copy() method:

In [31]:
an_array = np.array([[12,5,2,4], [7,6,8,8], [1,6,7,7]])
a_copy = an_array[:2,:2].copy()

a_copy

array([[12,  5],
       [ 7,  6]])

In [32]:
# If we now modify this subarray, the original array is not touched:
a_copy[0,0] = 42

print(a_copy)
print(an_array)

[[42  5]
 [ 7  6]]
[[12  5  2  4]
 [ 7  6  8  8]
 [ 1  6  7  7]]


Use both integer indexing & slice indexing

We can use combinations of integer indexing and slice indexing to create different shaped matrices.

In [34]:
# Create a Rank 2 array of shape (3, 4)
an_array = np.array([[11,12,13,14], [21,22,23,24], [31,32,33,34]])
print(an_array, an_array.shape)

[[11 12 13 14]
 [21 22 23 24]
 [31 32 33 34]] (3, 4)


In [35]:
# Using both integer indexing & slicing generates an array of lower rank
row_rank1 = an_array[0, :]    # Rank 1 view 

print(row_rank1, row_rank1.shape)  # notice only a single []

[11 12 13 14] (4,)


In [3]:
#We can do the same thing for columns of an array:
col_rank1 = an_array[:, 1]
col_rank2 = an_array[:, 1:2]

print(col_rank1, col_rank1.shape)  # Rank 1
print()
print(col_rank2, col_rank2.shape)  # Rank 2

[12 22 32] (3,)

[[12]
 [22]
 [32]] (3, 1)


Array Indexing for changing elements:

Sometimes it's useful to use an array of indexes to access or change elements.

In [5]:
# Create a new array
an_array = np.array([[11,12,13], [21,22,23], [31,32,33], [41,42,43]])

print('Original Array:')
print(an_array)

Original Array:
[[11 12 13]
 [21 22 23]
 [31 32 33]
 [41 42 43]]


In [6]:
# Create an array of indices
col_indices = np.array([0, 1, 2, 0])
print('\nCol indices picked : ', col_indices)

row_indices = np.arange(4)
print('\nRows indices picked : ', row_indices)


Col indices picked :  [0 1 2 0]

Rows indices picked :  [0 1 2 3]


In [6]:
# Examine the pairings of row_indices and col_indices.These are the elements we'll change next.
for row, col in zip(row_indices, col_indices):
    print(row, ", ", col)

0 ,  0
1 ,  1
2 ,  2
3 ,  0


In [12]:
# Select one element from each row
print('Values in the array at those indices: ',an_array[row_indices, col_indices])

[0 1 2 3]
Values in the array at those indices:  [11 22 33 41]


In [7]:
# Change one element from each row using the indices selected
an_array[row_indices, col_indices] += 100000

print('\nChanged Array:')
print(an_array)


Changed Array:
[[100011     12     13]
 [    21 100022     23]
 [    31     32 100033]
 [100041     42     43]]


### Boolean Indexing


Array Indexing for changing elements:

In [8]:
# create a 3x2 array
an_array = np.array([[11,12], [21, 22], [31, 32]])
print(an_array)

[[11 12]
 [21 22]
 [31 32]]
